import { escapeHtml } from "@/lib/email-escape";

/**
 * Images inside an admin email.
 *
 * An owner drops a picture into the message and it lands where they put it. The
 * carrier is a token in the message body:
 *
 *     [image:9f2c7a41b8e0d3f1-1120|Week 1 slate]
 *            \______________/ \__/ \___________/
 *              object handle  width   alt text
 *
 * Why a token rather than a table of image rows:
 *
 *   1. **Position is the whole feature.** Owners want the graphic *between* two
 *      paragraphs. A token is the only representation that keeps its place while
 *      the text around it is still being edited.
 *   2. **The audit row stays truthful for free.** `AdminBroadcast.body` already
 *      stores the exact text that was sent, so it now stores the images too —
 *      with no schema change, and no way for the record and the delivered mail
 *      to disagree.
 *   3. **No foreign `src` can reach an inbox.** The handle is an opaque id for an
 *      object in our own bucket and the URL is *derived* from it here — never
 *      read out of the message. Typed or pasted text cannot introduce another
 *      host, a `javascript:` URL, or an extra HTML attribute.
 *
 * The intrinsic width rides along inside the handle so the renderer can emit a
 * truthful `width` attribute (Outlook's Word engine ignores `max-width`) without
 * a second lookup at send time. That is what stops a 300px logo from being
 * stretched across a 560px email.
 *
 * Pure on purpose: no `server-only`, no network, no DB. The mailer renders with
 * it, the composer previews with it, and both agree because it is the same code.
 */

/** Content width of the email wrapper in `renderBroadcastHtml`. */
export const EMAIL_IMAGE_MAX_DISPLAY_WIDTH = 560;

/** Stored at 2x so the image is still sharp on a retina phone. */
export const EMAIL_IMAGE_MAX_STORED_WIDTH = 1120;

/** Alt text is a one-line description, not a caption. */
export const EMAIL_IMAGE_ALT_MAX_LENGTH = 120;

/**
 * Ceiling per email. Not a byte budget — images are hosted, so the HTML stays
 * small — but a mail with a dozen graphics is a mail nobody scrolls, and each one
 * is another request that has to succeed in every inbox.
 */
export const EMAIL_IMAGE_MAX_PER_EMAIL = 6;

/** `<16-32 hex chars>-<intrinsic width>`. Both halves are generated by us. */
const IMAGE_ID_PATTERN = /^([a-f0-9]{16,32})-([1-9]\d{1,3})$/;

/**
 * Deliberately looser than {@link IMAGE_ID_PATTERN}: a half-typed or stale token
 * has to be *matched* so it can be dropped, rather than left behind to ship to
 * the roster as the literal text `[image:oops]`.
 */
const IMAGE_TOKEN_PATTERN =
  /\[image:([A-Za-z0-9_-]{1,64})(?:\|([^\]\n]{0,200}))?\]/g;

export type EmailBodyBlock =
  | { kind: "text"; text: string }
  | { kind: "image"; id: string; alt: string; displayWidth: number };

/** True for a handle this module minted. Everything else is not ours to render. */
export function isEmailImageId(value: string): boolean {
  return IMAGE_ID_PATTERN.test(value);
}

/**
 * Mint a handle for a freshly stored image.
 *
 * `width` is the intrinsic width of the stored object, so the renderer can size
 * the image without reading the file again.
 */
export function buildEmailImageId(handle: string, width: number): string {
  const id = `${handle}-${Math.round(width)}`;
  if (!isEmailImageId(id)) {
    throw new Error(`refusing to mint an unusable email image id: ${id}`);
  }
  return id;
}

/** Width the image is stored at, or null when the id is not one of ours. */
export function emailImageIntrinsicWidth(id: string): number | null {
  const width = IMAGE_ID_PATTERN.exec(id)?.[2];
  return width ? Number(width) : null;
}

/**
 * Width to render at: the email's content width, or the image's own width when it
 * is narrower. Never upscales — a small logo stays small instead of being blown
 * up into a blurry 560px band.
 */
export function emailImageDisplayWidth(id: string): number | null {
  const intrinsic = emailImageIntrinsicWidth(id);
  if (intrinsic === null) return null;
  return Math.min(intrinsic, EMAIL_IMAGE_MAX_DISPLAY_WIDTH);
}

/**
 * Storage path for an id. Null for anything we did not mint, which is also what
 * keeps `../` and other path tricks out of a bucket key.
 */
export function emailImageObjectPath(id: string): string | null {
  if (!isEmailImageId(id)) return null;
  return `broadcasts/${id}.jpg`;
}

/**
 * Public URL for an image, given the bucket's public base.
 *
 * The whole URL is derivable from the handle, which is why an owner can reopen a
 * saved template weeks later and still see its pictures: nothing has to remember
 * where an image went, because the marker already says.
 */
export function emailImageUrlFrom(baseUrl: string, id: string): string | null {
  const path = emailImageObjectPath(id);
  if (!path) return null;
  return `${baseUrl.replace(/\/+$/, "")}/${path}`;
}

/**
 * Fold a description down to what the token grammar can carry: one line, no `]`
 * or `|` to close the token early, and short enough to stay a description.
 */
export function sanitizeEmailImageAlt(alt: string): string {
  return alt
    .replace(/[\r\n\t]+/g, " ")
    .replace(/[[\]|]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, EMAIL_IMAGE_ALT_MAX_LENGTH)
    .trim();
}

/** The text an owner sees in the message box for one inserted image. */
export function formatEmailImageToken(id: string, alt: string): string {
  const description = sanitizeEmailImageAlt(alt);
  return description ? `[image:${id}|${description}]` : `[image:${id}]`;
}

/** A filename is a better first draft of alt text than an empty string. */
export function altTextFromFileName(fileName: string): string {
  const base = fileName.replace(/\.[a-z0-9]{1,5}$/i, "");
  return sanitizeEmailImageAlt(base.replace(/[_-]+/g, " "));
}

/**
 * Drop a token into the message at the cursor, as its own block.
 *
 * Blank lines are added around it only where they are missing, so inserting into
 * the middle of a sentence splits it cleanly instead of burying the image inside
 * a paragraph — and inserting twice in a row does not stack up empty lines. The
 * returned caret sits after the insertion so typing continues below the picture.
 */
export function insertEmailImageToken(
  text: string,
  selectionStart: number,
  selectionEnd: number,
  token: string,
): { text: string; caret: number } {
  const start = Math.max(0, Math.min(selectionStart, text.length));
  const end = Math.max(start, Math.min(selectionEnd, text.length));
  // Spaces sitting against a break we are about to add are invisible in the box
  // and would survive into the sent mail. Only horizontal whitespace goes: the
  // newlines already there are what tells us how much separation to add.
  const before = text.slice(0, start).replace(/[ \t]+$/, "");
  const after = text.slice(end).replace(/^[ \t]+/, "");

  const prefix = !before
    ? ""
    : before.endsWith("\n\n")
      ? ""
      : before.endsWith("\n")
        ? "\n"
        : "\n\n";
  const suffix = !after
    ? ""
    : after.startsWith("\n\n")
      ? ""
      : after.startsWith("\n")
        ? "\n"
        : "\n\n";

  const inserted = `${prefix}${token}${suffix}`;
  return {
    text: `${before}${inserted}${after}`,
    caret: before.length + inserted.length,
  };
}

/** Matches every token for one image, whatever alt text it currently carries. */
function tokenPatternFor(id: string): RegExp {
  const literal = id.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`\\[image:${literal}(?:\\|[^\\]\\n]{0,200})?\\]`, "g");
}

/**
 * Rewrite one image's token in place — used when an owner edits its description,
 * so the alt text they typed is the alt text that ships.
 */
export function replaceEmailImageToken(
  text: string,
  id: string,
  alt: string,
): string {
  const token = formatEmailImageToken(id, alt);
  // A replacer function, not a replacement string: `String.replace` reads `$&`,
  // "$`" and `$'` in a string replacement as substitution patterns, so a
  // description like "$5 off — $& more" would come back mangled. A function's
  // return value is taken literally.
  return text.replace(tokenPatternFor(id), () => token);
}

/** Remove every reference to one image, and the blank lines it left behind. */
export function removeEmailImageToken(text: string, id: string): string {
  return text
    .replace(tokenPatternFor(id), "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/^\n+/, "")
    .replace(/\n+$/, "");
}

/**
 * Split a message into the sequence of paragraphs and images it renders as.
 *
 * Blank lines separate paragraphs; a single newline stays inside one. An image
 * token breaks the paragraph it sits in, so a token on its own line and a token
 * typed mid-sentence both come out as a block-level image — the one layout every
 * mail client agrees on.
 */
export function parseEmailBodyBlocks(body: string): EmailBodyBlock[] {
  const blocks: EmailBodyBlock[] = [];

  const pushText = (raw: string) => {
    for (const paragraph of raw.split(/\n{2,}/)) {
      const text = paragraph.trim();
      if (text) blocks.push({ kind: "text", text });
    }
  };

  let cursor = 0;
  // A fresh regex per call: a shared literal with `g` carries `lastIndex`, and
  // reusing it across calls silently skips the first token of the next message.
  const pattern = new RegExp(IMAGE_TOKEN_PATTERN.source, "g");
  for (const match of body.matchAll(pattern)) {
    const at = match.index ?? 0;
    pushText(body.slice(cursor, at));
    cursor = at + match[0].length;

    const id = match[1] ?? "";
    const displayWidth = emailImageDisplayWidth(id);
    // Unknown handle: drop the token. Shipping raw `[image:...]` text to the
    // roster is worse than a missing picture, and the composer preview shows it
    // disappear while there is still time to fix it.
    if (displayWidth === null) continue;
    blocks.push({
      kind: "image",
      id,
      alt: sanitizeEmailImageAlt(match[2] ?? ""),
      displayWidth,
    });
  }
  pushText(body.slice(cursor));

  return blocks;
}

/**
 * Does this text contain an image marker at all?
 *
 * Matches the loose token shape, not a valid handle, so a stale or half-typed
 * marker still routes through the image path and gets dropped there rather than
 * being rendered as literal `[image:…]` text.
 */
export function hasEmailImageMarker(text: string): boolean {
  return new RegExp(IMAGE_TOKEN_PATTERN.source).test(text);
}

/** Every image this message references, in order, without duplicates. */
export function collectEmailImageIds(body: string): string[] {
  const ids: string[] = [];
  for (const block of parseEmailBodyBlocks(body)) {
    if (block.kind === "image" && !ids.includes(block.id)) ids.push(block.id);
  }
  return ids;
}

/**
 * Render the message body to email HTML.
 *
 * `imageUrl` resolves a handle to its public URL; returning null drops that
 * image rather than emitting a broken `<img>`.
 */
export function renderEmailBodyHtml(
  body: string,
  imageUrl: (id: string) => string | null,
): string {
  return parseEmailBodyBlocks(body)
    .map((block) => {
      if (block.kind === "text") {
        const text = escapeHtml(block.text).replace(/\n/g, "<br />");
        return `<p style="line-height:1.6">${text}</p>`;
      }

      const src = imageUrl(block.id);
      if (!src) return "";
      return renderEmailImageHtml(block, src);
    })
    .filter(Boolean)
    .join("");
}

/**
 * The `<img>` an inbox receives. One implementation, so a picture in an
 * automated template and a picture in a mass email are laid out identically.
 *
 * `width` is for Outlook's Word engine, which ignores `max-width`; the style
 * then lets every other client shrink it on a narrow phone. `display:block`
 * kills the descender gap under an inline image, and `border:0` stops Outlook
 * drawing a frame around it.
 */
export function renderEmailImageHtml(
  block: { alt: string; displayWidth: number },
  src: string,
): string {
  return [
    `<p style="margin:0 0 16px">`,
    `<img src="${escapeHtml(src)}"`,
    ` alt="${escapeHtml(block.alt)}"`,
    ` width="${block.displayWidth}"`,
    ` style="display:block;width:100%;max-width:${block.displayWidth}px;height:auto;border:0;border-radius:8px" />`,
    `</p>`,
  ].join("");
}

/** How an image reads in the plain-text twin, where there is no picture. */
export function emailImageTextFallback(alt: string): string {
  const description = sanitizeEmailImageAlt(alt);
  return description ? `[Image: ${description}]` : "[Image]";
}
