import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import bcrypt from "bcryptjs";

import {
  LEGACY_PASSWORD_FORMATS,
  detectLegacyPasswordFormat,
  phpassCrypt,
  verifyLegacyPassword,
} from "@/lib/legacy-password";
import { LEGACY_PASSWORD_FORMATS as IMPORT_FORMATS } from "@/lib/schemas/legacy-import.schema";

const PASSWORD = "oldpass1";

test("the import contract accepts exactly the formats the verifier supports", () => {
  // The list is duplicated because the import schema stays path-alias free;
  // a format the importer accepts but login can't check would lock people out.
  assert.deepEqual([...IMPORT_FORMATS], [...LEGACY_PASSWORD_FORMATS]);
});

test("formats are detected from the shape of the stored hash", () => {
  const bcryptHash = bcrypt.hashSync(PASSWORD, 4);
  assert.equal(detectLegacyPasswordFormat(bcryptHash), "BCRYPT");
  assert.equal(
    detectLegacyPasswordFormat(`$2y$${bcryptHash.slice(4)}`),
    "BCRYPT",
  );
  assert.equal(
    detectLegacyPasswordFormat("$P$B7pQm3zGkFhX1sN0oJvUd2LcYtRw9e/"),
    "PHPASS",
  );
  assert.equal(
    detectLegacyPasswordFormat(
      createHash("md5").update(PASSWORD).digest("hex"),
    ),
    "MD5",
  );
  assert.equal(
    detectLegacyPasswordFormat(
      createHash("sha1").update(PASSWORD).digest("hex"),
    ),
    "SHA1",
  );
  assert.equal(
    detectLegacyPasswordFormat(
      createHash("sha256").update(PASSWORD).digest("hex"),
    ),
    "SHA256",
  );
  // Never guess plaintext: an unrecognised string fails closed.
  assert.equal(detectLegacyPasswordFormat(PASSWORD), null);
  assert.equal(detectLegacyPasswordFormat(""), null);
});

test("bcrypt hashes from PHP's password_hash ($2y$) verify", async () => {
  const hash = `$2y$${bcrypt.hashSync(PASSWORD, 4).slice(4)}`;
  assert.equal(await verifyLegacyPassword(PASSWORD, hash), true);
  assert.equal(await verifyLegacyPassword("wrong", hash), false);
});

/*
 * Fixtures generated by the reference phpass 0.5 `crypt_private` running under
 * PHP — the implementation WordPress and phpBB3 ship. Hashing against our own
 * code and verifying with it again would pass on any self-consistent algorithm;
 * these pin the byte-for-byte output an imported hash will actually have.
 */
const PHPASS_VECTORS: { password: string; hash: string }[] = [
  { password: PASSWORD, hash: "$P$B7pQm3zGkPYNhJMYGokznrdh9KXBD60" },
  // phpBB's $H$ variant is the same scheme, same digest.
  { password: PASSWORD, hash: "$H$B7pQm3zGkPYNhJMYGokznrdh9KXBD60" },
  {
    password: "correct horse battery staple",
    hash: "$P$Djjjjjjjj/LowiMD/BV9haVHb7mmDn1",
  },
  // Lowest accepted iteration count (log2 = 7).
  { password: "x", hash: "$P$9saltsaltplSRmHJkt5TtboIt8HNc.." },
];

test("phpass hashing reproduces the PHP reference output", () => {
  for (const { password, hash } of PHPASS_VECTORS) {
    assert.equal(phpassCrypt(password, hash), hash);
  }
});

test("phpass portable hashes verify", async () => {
  for (const { password, hash } of PHPASS_VECTORS) {
    assert.equal(await verifyLegacyPassword(password, hash), true);
    assert.equal(await verifyLegacyPassword(`${password}x`, hash), false);
  }
});

test("phpass rejects settings outside the supported iteration range", () => {
  // itoa64 index of "." is 0 — below the log2 floor of 7.
  assert.equal(
    phpassCrypt(PASSWORD, "$P$.saltsaltXXXXXXXXXXXXXXXXXXXXXX"),
    null,
  );
  assert.equal(
    phpassCrypt(PASSWORD, "$Q$B7pQm3zGkFhX1sN0oJvUd2LcYtRw9e/"),
    null,
  );
});

test("unsalted digests verify, case-insensitively on the stored side", async () => {
  const md5 = createHash("md5").update(PASSWORD).digest("hex");
  assert.equal(await verifyLegacyPassword(PASSWORD, md5.toUpperCase()), true);
  assert.equal(await verifyLegacyPassword("wrong", md5), false);

  const sha1 = createHash("sha1").update(PASSWORD).digest("hex");
  assert.equal(await verifyLegacyPassword(PASSWORD, sha1), true);

  const sha256 = createHash("sha256").update(PASSWORD).digest("hex");
  assert.equal(await verifyLegacyPassword(PASSWORD, sha256), true);
});

test("plaintext only verifies when the import declares it", async () => {
  assert.equal(await verifyLegacyPassword(PASSWORD, PASSWORD), false);
  assert.equal(
    await verifyLegacyPassword(PASSWORD, PASSWORD, "PLAINTEXT"),
    true,
  );
  assert.equal(
    await verifyLegacyPassword("wrong", PASSWORD, "PLAINTEXT"),
    false,
  );
});

test("missing, empty, and uncheckable hashes fail closed", async () => {
  assert.equal(await verifyLegacyPassword(PASSWORD, null), false);
  assert.equal(await verifyLegacyPassword(PASSWORD, ""), false);
  assert.equal(await verifyLegacyPassword(PASSWORD, "   "), false);
  assert.equal(await verifyLegacyPassword("", "anything"), false);
  // A declared format that can't parse the value must not fall through to a match.
  assert.equal(
    await verifyLegacyPassword(PASSWORD, "not-a-hash", "PHPASS"),
    false,
  );
  assert.equal(
    await verifyLegacyPassword(PASSWORD, "$P$short", "PHPASS"),
    false,
  );
});
