-- Generated by running the corrected matcher (PR #430) against ESPN final scores.
-- Each statement is idempotent: the UPDATE only fires while the play is still PENDING.
BEGIN;

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-2.78, "gradedAt"=now() WHERE id='cmsfbuufl0001elx0weio88xg' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbuufl0001elx0weio88xg'),1,18),'cmsfbuufl0001elx0weio88xg','PENDING','LOSS',NULL,-2.78,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Los Angeles Dodgers',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbuufl0001elx0weio88xg' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=5.00, "gradedAt"=now() WHERE id='cmsfbv84f000felx04rcpnahh' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbv84f000felx04rcpnahh'),1,18),'cmsfbv84f000felx04rcpnahh','PENDING','WIN',NULL,5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Texas Rangers',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbv84f000felx04rcpnahh' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-8.20, "gradedAt"=now() WHERE id='cmsfbv84f000ielx0zdu09ekz' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbv84f000ielx0zdu09ekz'),1,18),'cmsfbv84f000ielx0zdu09ekz','PENDING','LOSS',NULL,-8.20,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Los Angeles Dodgers',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbv84f000ielx0zdu09ekz' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=7.10, "gradedAt"=now() WHERE id='cmsfbv84f000jelx0a08cak86' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbv84f000jelx0a08cak86'),1,18),'cmsfbv84f000jelx0a08cak86','PENDING','WIN',NULL,7.10,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Detroit Tigers',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbv84f000jelx0a08cak86' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-5.00, "gradedAt"=now() WHERE id='cmsfbv84f000kelx08thxosw0' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbv84f000kelx08thxosw0'),1,18),'cmsfbv84f000kelx08thxosw0','PENDING','LOSS',NULL,-5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Arizona Diamondbacks',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbv84f000kelx08thxosw0' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=5.00, "gradedAt"=now() WHERE id='cmsfbvb990014elx0srj2kqan' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvb990014elx0srj2kqan'),1,18),'cmsfbvb990014elx0srj2kqan','PENDING','WIN',NULL,5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Toronto Tempo +13',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvb990014elx0srj2kqan' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-5.00, "gradedAt"=now() WHERE id='cmsfbvcoq0018elx0pljfdqoq' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvcoq0018elx0pljfdqoq'),1,18),'cmsfbvcoq0018elx0pljfdqoq','PENDING','LOSS',NULL,-5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). San Francisco Giants',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvcoq0018elx0pljfdqoq' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=2.00, "gradedAt"=now() WHERE id='cmsfbvf0a001delx041xa1kqq' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvf0a001delx041xa1kqq'),1,18),'cmsfbvf0a001delx041xa1kqq','PENDING','WIN',NULL,2.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Houston Astros',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvf0a001delx041xa1kqq' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=4.98, "gradedAt"=now() WHERE id='cmsfbvlx9001helx03ys8z6vw' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvlx9001helx03ys8z6vw'),1,18),'cmsfbvlx9001helx03ys8z6vw','PENDING','WIN',NULL,4.98,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Chicago Cubs',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvlx9001helx03ys8z6vw' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=5.00, "gradedAt"=now() WHERE id='cmsfbvlx9001ielx0lgsbuhx3' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvlx9001ielx0lgsbuhx3'),1,18),'cmsfbvlx9001ielx0lgsbuhx3','PENDING','WIN',NULL,5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). San Francisco Giants +1.5',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvlx9001ielx0lgsbuhx3' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-4.00, "gradedAt"=now() WHERE id='cmsfbvlx9001kelx0n8q7gem2' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvlx9001kelx0n8q7gem2'),1,18),'cmsfbvlx9001kelx0n8q7gem2','PENDING','LOSS',NULL,-4.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Toronto Blue Jays',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvlx9001kelx0n8q7gem2' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=5.55, "gradedAt"=now() WHERE id='cmsfbvlx9001lelx0fybcyfse' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvlx9001lelx0fybcyfse'),1,18),'cmsfbvlx9001lelx0fybcyfse','PENDING','WIN',NULL,5.55,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Detroit Tigers',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvlx9001lelx0fybcyfse' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-3.00, "gradedAt"=now() WHERE id='cmsfbvlx9001melx047zbravi' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvlx9001melx047zbravi'),1,18),'cmsfbvlx9001melx047zbravi','PENDING','LOSS',NULL,-3.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Arizona Diamondbacks -1.5',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvlx9001melx047zbravi' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-5.70, "gradedAt"=now() WHERE id='cmsfbvlx9001nelx0yx4io2fl' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvlx9001nelx0yx4io2fl'),1,18),'cmsfbvlx9001nelx0yx4io2fl','PENDING','LOSS',NULL,-5.70,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Arizona Diamondbacks',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvlx9001nelx0yx4io2fl' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=1.00, "gradedAt"=now() WHERE id='cmsfbvvuk001telx09kbwzgvo' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvvuk001telx09kbwzgvo'),1,18),'cmsfbvvuk001telx09kbwzgvo','PENDING','WIN',NULL,1.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Tampa Bay Rays',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvvuk001telx09kbwzgvo' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=0.54, "gradedAt"=now() WHERE id='cmsfbvvuk001uelx03as05pr1' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvvuk001uelx03as05pr1'),1,18),'cmsfbvvuk001uelx03as05pr1','PENDING','WIN',NULL,0.54,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Detroit Tigers',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvvuk001uelx03as05pr1' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=1.00, "gradedAt"=now() WHERE id='cmsfbvyy60022elx0gs4noyq3' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvyy60022elx0gs4noyq3'),1,18),'cmsfbvyy60022elx0gs4noyq3','PENDING','WIN',NULL,1.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Houston Astros',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvyy60022elx0gs4noyq3' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-1.10, "gradedAt"=now() WHERE id='cmsfbvyy60023elx0ryj809jg' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvyy60023elx0ryj809jg'),1,18),'cmsfbvyy60023elx0ryj809jg','PENDING','LOSS',NULL,-1.10,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Colorado Rockies +1.5',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvyy60023elx0ryj809jg' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=1.05, "gradedAt"=now() WHERE id='cmsfbvyy60024elx0i44mj6tb' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvyy60024elx0i44mj6tb'),1,18),'cmsfbvyy60024elx0i44mj6tb','PENDING','WIN',NULL,1.05,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). San Diego Padres',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvyy60024elx0i44mj6tb' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-4.48, "gradedAt"=now() WHERE id='cmsfbw2g70029elx0uni272ad' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbw2g70029elx0uni272ad'),1,18),'cmsfbw2g70029elx0uni272ad','PENDING','LOSS',NULL,-4.48,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Arizona Diamondbacks',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbw2g70029elx0uni272ad' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-1.41, "gradedAt"=now() WHERE id='cmsfbwach002ielx050b6wbvv' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbwach002ielx050b6wbvv'),1,18),'cmsfbwach002ielx050b6wbvv','PENDING','LOSS',NULL,-1.41,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Minnesota Twins',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbwach002ielx050b6wbvv' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=1.00, "gradedAt"=now() WHERE id='cmsfbwcvx002melx06w7hfhfx' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbwcvx002melx06w7hfhfx'),1,18),'cmsfbwcvx002melx06w7hfhfx','PENDING','WIN',NULL,1.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Houston Astros',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbwcvx002melx06w7hfhfx' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=1.00, "gradedAt"=now() WHERE id='cmsfbuufl0000elx0bg0g9hqw' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbuufl0000elx0bg0g9hqw'),1,18),'cmsfbuufl0000elx0bg0g9hqw','PENDING','WIN',NULL,1.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Milwaukee Brewers',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbuufl0000elx0bg0g9hqw' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-4.00, "gradedAt"=now() WHERE id='cmsfbvlx9001jelx0862e449g' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvlx9001jelx0862e449g'),1,18),'cmsfbvlx9001jelx0862e449g','PENDING','LOSS',NULL,-4.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). San Francisco Giants',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvlx9001jelx0862e449g' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-3.45, "gradedAt"=now() WHERE id='cmsfbw2g7002aelx0utgwws7p' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbw2g7002aelx0utgwws7p'),1,18),'cmsfbw2g7002aelx0utgwws7p','PENDING','LOSS',NULL,-3.45,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Golden State Valkyries -11.5',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbw2g7002aelx0utgwws7p' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=5.00, "gradedAt"=now() WHERE id='cmsfbv84f000delx00zgjpep3' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbv84f000delx00zgjpep3'),1,18),'cmsfbv84f000delx00zgjpep3','PENDING','WIN',NULL,5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). New York Yankees',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbv84f000delx00zgjpep3' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-5.00, "gradedAt"=now() WHERE id='cmsfbvcoq0016elx023m94g18' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvcoq0016elx023m94g18'),1,18),'cmsfbvcoq0016elx023m94g18','PENDING','LOSS',NULL,-5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). St Louis Cardinals',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvcoq0016elx023m94g18' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-5.00, "gradedAt"=now() WHERE id='cmsfbvcoq0017elx0ubkolhha' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvcoq0017elx0ubkolhha'),1,18),'cmsfbvcoq0017elx0ubkolhha','PENDING','LOSS',NULL,-5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Miami Marlins',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvcoq0017elx0ubkolhha' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=2.00, "gradedAt"=now() WHERE id='cmsfbvf0a001celx0wwtdakx7' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvf0a001celx0wwtdakx7'),1,18),'cmsfbvf0a001celx0wwtdakx7','PENDING','WIN',NULL,2.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Atlanta Braves',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvf0a001celx0wwtdakx7' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=1.00, "gradedAt"=now() WHERE id='cmsfbvvuk001selx0y53dw2gt' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbvvuk001selx0y53dw2gt'),1,18),'cmsfbvvuk001selx0y53dw2gt','PENDING','WIN',NULL,1.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Atlanta Braves',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbvvuk001selx0y53dw2gt' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=3.00, "gradedAt"=now() WHERE id='cmsfbw2g70028elx0zrwd3lxa' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbw2g70028elx0zrwd3lxa'),1,18),'cmsfbw2g70028elx0zrwd3lxa','PENDING','WIN',NULL,3.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Milwaukee Brewers',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbw2g70028elx0zrwd3lxa' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=5.00, "gradedAt"=now() WHERE id='cmsfbw73x002eelx0p8atdfau' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbw73x002eelx0p8atdfau'),1,18),'cmsfbw73x002eelx0p8atdfau','PENDING','WIN',NULL,5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Atlanta Braves',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbw73x002eelx0p8atdfau' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=5.00, "gradedAt"=now() WHERE id='cmsfbw73x002felx014kcxi53' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbw73x002felx014kcxi53'),1,18),'cmsfbw73x002felx014kcxi53','PENDING','WIN',NULL,5.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Milwaukee Brewers',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbw73x002felx014kcxi53' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=3.00, "gradedAt"=now() WHERE id='cmsfbw8py002gelx02mjdkq0h' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbw8py002gelx02mjdkq0h'),1,18),'cmsfbw8py002gelx02mjdkq0h','PENDING','WIN',NULL,3.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Atlanta Braves',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbw8py002gelx02mjdkq0h' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=7.50, "gradedAt"=now() WHERE id='cmsfbv84f000eelx0lp8orq1y' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbv84f000eelx0lp8orq1y'),1,18),'cmsfbv84f000eelx0lp8orq1y','PENDING','WIN',NULL,7.50,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Kansas City Royals',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbv84f000eelx0lp8orq1y' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=2.50, "gradedAt"=now() WHERE id='cmsggl6250003elr4202ulu3b' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsggl6250003elr4202ulu3b'),1,18),'cmsggl6250003elr4202ulu3b','PENDING','WIN',NULL,2.50,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). TBR -147',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsggl6250003elr4202ulu3b' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-1.17, "gradedAt"=now() WHERE id='cmsggl6250004elr4ptskipq0' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsggl6250004elr4ptskipq0'),1,18),'cmsggl6250004elr4ptskipq0','PENDING','LOSS',NULL,-1.17,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). SDP -117',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsggl6250004elr4ptskipq0' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=11.50, "gradedAt"=now() WHERE id='cmsgglffd0005elr4r2a9yuvj' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsgglffd0005elr4r2a9yuvj'),1,18),'cmsgglffd0005elr4r2a9yuvj','PENDING','WIN',NULL,11.50,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Toronto Blue Jays',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsgglffd0005elr4r2a9yuvj' AND outcome='WIN');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=1.00, "gradedAt"=now() WHERE id='cmsgglxto000oelr4lrciig0u' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsgglxto000oelr4lrciig0u'),1,18),'cmsgglxto000oelr4lrciig0u','PENDING','WIN',NULL,1.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). TBR -147',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsgglxto000oelr4lrciig0u' AND outcome='WIN');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-4.00, "gradedAt"=now() WHERE id='cmsgglyz5000pelr45wc0orrf' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsgglyz5000pelr45wc0orrf'),1,18),'cmsgglyz5000pelr45wc0orrf','PENDING','LOSS',NULL,-4.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Houston Astros -1.5',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsgglyz5000pelr45wc0orrf' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-9.10, "gradedAt"=now() WHERE id='cmsgglyz5000qelr4bj265l2s' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsgglyz5000qelr4bj265l2s'),1,18),'cmsgglyz5000qelr4bj265l2s','PENDING','LOSS',NULL,-9.10,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Houston Astros',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsgglyz5000qelr4bj265l2s' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='LOSS', "profitUnits"=-9.25, "gradedAt"=now() WHERE id='cmsggmhc9001felr4q5fvrw2l' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsggmhc9001felr4q5fvrw2l'),1,18),'cmsggmhc9001felr4q5fvrw2l','PENDING','LOSS',NULL,-9.25,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Houston Astros',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsggmhc9001felr4q5fvrw2l' AND outcome='LOSS');

UPDATE scl."Play" SET outcome='WIN', "profitUnits"=2.00, "gradedAt"=now() WHERE id='cmsfbw2g7002belx0ok4htfp7' AND outcome='PENDING';
INSERT INTO scl."GradingAudit" (id,"playId","previousOutcome","newOutcome","previousProfitUnits","newProfitUnits",source,"gradedById",reason,"createdAt")
SELECT 'bf'||substr(md5('cmsfbw2g7002belx0ok4htfp7'),1,18),'cmsfbw2g7002belx0ok4htfp7','PENDING','WIN',NULL,2.00,'AUTO',NULL,'Backfill: settled from ESPN final scores using the corrected fixture matcher (PR #430). Golden State Valkyries -7',now()
WHERE EXISTS (SELECT 1 FROM scl."Play" WHERE id='cmsfbw2g7002belx0ok4htfp7' AND outcome='WIN');

COMMIT;
